logging:
  level:
    tk.mybatis: debug
    com.loop.demo.admin: debug
spring:
  application:
    name: loop-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 2
    host: ${REDIS_HOST:192.168.31.241}
    password:
    port: ${REDIS_PORT:6379}
    pool:
    max-active: 20
  datasource:
#    name: test
    url: jdbc:mysql://${MYSQL_HOST:192.168.31.241}:${MYSQL_PORT:3306}/loop_admin_v1?useUnicode=true&characterEncoding=UTF8
#    url: jdbc:mysql://${MYSQL_HOST:120.79.250.60}:${MYSQL_PORT:3306}/loop_admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 5601564a
    #阿里巴巴数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#  Actuator 开放所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
endpoints:
  health:
    sensitive: false

mybatis:
  basepackage: com.loop.demo.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 9002

jwt:
  token-header: Authorization
  expire: 14400  #四个小时
  rsa-secret: xx1WET12^%3^(WE45
#不需要登录验证的地址
url:
  ignore:
    startWith: /jwt

